apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontends
  namespace: expense
  # labels of deployment resource
  labels:
    app: frontends
    tier: web
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontends
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontends
        tier: web
        project: expense
    spec:
      containers:
      - name: nginx
        image: saikumargama99/frontends:1.1.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: frontends
  namespace: expense
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: frontends
    tier: web
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 8080